services:
  - type: web
    name: telegram-ticket-bot
    env: python
    buildCommand: |
  pip install -r requirements.txt
  playwright install
    startCommand: python main.py
    plan: free
    autoDeploy: true
