services:
  - type: web
    name: telegram-ticket-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python main.py
    plan: free
    autoDeploy: true
